apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-4
  namespace: kafka
  labels:
    app: kafka-broker-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-4
  template:
    metadata:
      labels:
        app: kafka-broker-4
    spec:
      hostname: kafka-broker-4
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.2
          ports:
            - containerPort: 9094
            - containerPort: 29094
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-1:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9095"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-4:29095,PLAINTEXT_HOST://192.168.0.165:9095"
            - name: KAFKA_BROKER_ID
              value: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-4
  namespace: kafka
  labels:
    app: kafka-broker-4
spec:
  type: LoadBalancer
  ports:
    - port: 9095
      targetPort: 9095
  selector:
    app: kafka-broker-4