apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pmtv-selfsigned-cert
spec:
  isCA: true
  dnsNames:
    - paymetv.co.uk #hostname
  secretName: pmtv-ss-sec
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: pmtv-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    organizations:
      - Devops-Avenue