apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: monitoring
  labels:
    app: fastapi-app
spec:
  type: LoadBalancer
  selector:
    app: fastapi-app
  ports:
  - name: web
    protocol: TCP
    port: 8000
    targetPort: 8000
