apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-monitoring-ui
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-broker-1:29092,kafka-broker-2:29093,kafka-broker-3:29094"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper-1:2181"
            - name: AUTH_TYPE
              value: "LOGIN_FORM"
            - name: SPRING_SECURITY_USER_NAME
              value: "kafka_user"
            - name: SPRING_SECURITY_USER_PASSWORD
              value: "kafka_password"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: kafka-ui
  type: LoadBalancer