apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace kafka -f docker-compose.yml
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: kafka
  name: kafka
  namespace: kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: kafka
