apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pmtv-acme-http-stag
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #server: https://acme-v02.api.letsencrypt.org/directory # production issuer
    email: mail@paymetv.co.uk #required to register account
    privateKeySecretRef:
      name: pmtv-acme-http-stag-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx  # Other options: class; name(ingress_resource); podtemplate(change or add to the labels and annotations of solver pods) + Gateway API