apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pmtv-acme-http-prod-cert
spec:
  dnsNames:
    - paymetv.co.uk
  secretName: pmtv-acme-http-prod-sec
  issuerRef:
    name: pmtv-acme-http-prod
    kind: ClusterIssuer