apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymetv-app-deployment
  labels:
    app: paymetv-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymetv-app
  template:
    metadata:
      labels:
        app: paymetv-app
    spec:
      containers:
        - name: paymetv-app
          image: paymetv/paymetv-app:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
              # Health probes using Spring Boot Actuator
          # Health probes using Spring Boot Actuator
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Resource limits for better pod management
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymetv-app-service
  labels:
    app: paymetv-app
spec:
  type: LoadBalancer # Use NodePort if LoadBalancer is not available in your cluster
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: paymetv-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paymetv-app-ingress
  labels:
    app: paymetv-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: ${SECRET_NAME}
      hosts:
        - paymetv.co.uk
  rules:
    - host: paymetv.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paymetv-app-service
                port:
                  number: 80