apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paymetv-app-cert
  namespace: default
spec:
  secretName: paymetv-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: paymetv.co.uk
  dnsNames:
    - paymetv.co.uk